version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bug-bounty-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      W3ID_CLIENT_ID: ${W3ID_CLIENT_ID}
      W3ID_CLIENT_SECRET: ${W3ID_CLIENT_SECRET}
      W3ID_REDIRECT_URI: ${W3ID_REDIRECT_URI}
      MENDSCAN_API_URL: ${MENDSCAN_API_URL}
      MENDSCAN_API_KEY: ${MENDSCAN_API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      FRONTEND_URL: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      MAX_FILE_SIZE: 5242880
      UPLOAD_PATH: ./uploads
      RANKING_UPDATE_CRON: "0 0 */15 * * *"
      MVP_UPDATE_CRON: "0 0 1 * * *"
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - bug-bounty-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bug-bounty-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000/api
      VITE_SOCKET_URL: http://localhost:4000
      VITE_AUTH_DOMAIN: ${W3ID_CLIENT_ID}
      VITE_AUTH_CLIENT_ID: ${W3ID_CLIENT_ID}
      VITE_MENDSCAN_API_URL: ${MENDSCAN_API_URL}
      VITE_MENDSCAN_API_KEY: ${MENDSCAN_API_KEY}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bug-bounty-network

networks:
  bug-bounty-network:
    driver: bridge 