import React from "react";
import RankingTable, { RankingRow } from './RankingTable';

// Datos mock para las tablas de ranking (equipos)
const teamsRanking: RankingRow[] = [
  {
    position: 1,
    name: 'CyberDragons',
    icon: '🐉',
    resolved: 120,
    resolvedGoal: 150,
    points: 3200,
    weeklyChange: 15,
    effectiveness: 98,
    effectivenessIcon: '🎯',
    remaining: 30,
    remainingGoal: 150,
    lastUpdate: 'Hace 10 min',
  },
  {
    position: 2,
    name: 'RocketSec',
    icon: '🚀',
    resolved: 110,
    resolvedGoal: 150,
    points: 2950,
    weeklyChange: 10,
    effectiveness: 92,
    effectivenessIcon: '🌟',
    remaining: 40,
    remainingGoal: 150,
    lastUpdate: 'Hace 12 min',
  },
  {
    position: 3,
    name: 'GearGuardians',
    icon: '⚙️',
    resolved: 100,
    resolvedGoal: 150,
    points: 2700,
    weeklyChange: -5,
    effectiveness: 89,
    effectivenessIcon: '💡',
    remaining: 50,
    remainingGoal: 150,
    lastUpdate: 'Hace 15 min',
  },
  {
    position: 4,
    name: 'Shielders',
    icon: '🛡️',
    resolved: 90,
    resolvedGoal: 150,
    points: 2200,
    weeklyChange: 0,
    effectiveness: 85,
    effectivenessIcon: '🌟',
    remaining: 60,
    remainingGoal: 150,
    lastUpdate: 'Hace 20 min',
  },
  {
    position: 5,
    name: 'PhantomHunters',
    icon: '👻',
    resolved: 85,
    resolvedGoal: 150,
    points: 2100,
    weeklyChange: 8,
    effectiveness: 82,
    effectivenessIcon: '⚡',
    remaining: 65,
    remainingGoal: 150,
    lastUpdate: 'Hace 25 min',
  },
  {
    position: 6,
    name: 'NeonKnights',
    icon: '⚔️',
    resolved: 80,
    resolvedGoal: 150,
    points: 1950,
    weeklyChange: -3,
    effectiveness: 78,
    effectivenessIcon: '💎',
    remaining: 70,
    remainingGoal: 150,
    lastUpdate: 'Hace 30 min',
  },
  {
    position: 7,
    name: 'ShadowStrikers',
    icon: '🌑',
    resolved: 75,
    resolvedGoal: 150,
    points: 1800,
    weeklyChange: 12,
    effectiveness: 75,
    effectivenessIcon: '🎭',
    remaining: 75,
    remainingGoal: 150,
    lastUpdate: 'Hace 35 min',
  },
  {
    position: 8,
    name: 'VoidRunners',
    icon: '🌀',
    resolved: 70,
    resolvedGoal: 150,
    points: 1650,
    weeklyChange: -8,
    effectiveness: 72,
    effectivenessIcon: '🌪️',
    remaining: 80,
    remainingGoal: 150,
    lastUpdate: 'Hace 40 min',
  },
  {
    position: 9,
    name: 'CrystalGuardians',
    icon: '💎',
    resolved: 65,
    resolvedGoal: 150,
    points: 1500,
    weeklyChange: 5,
    effectiveness: 68,
    effectivenessIcon: '✨',
    remaining: 85,
    remainingGoal: 150,
    lastUpdate: 'Hace 45 min',
  },
  {
    position: 10,
    name: 'ThunderBolt',
    icon: '⚡',
    resolved: 60,
    resolvedGoal: 150,
    points: 1350,
    weeklyChange: -2,
    effectiveness: 65,
    effectivenessIcon: '🔥',
    remaining: 90,
    remainingGoal: 150,
    lastUpdate: 'Hace 50 min',
  },
];

// Datos mock para las tablas de ranking (usuarios)
const usersRanking: RankingRow[] = [
  {
    position: 1,
    name: 'NinjaSec',
    icon: '🦸‍♂️',
    resolved: 80,
    resolvedGoal: 100,
    points: 2100,
    weeklyChange: 8,
    effectiveness: 99,
    effectivenessIcon: '🎯',
    remaining: 20,
    remainingGoal: 100,
    lastUpdate: 'Hace 5 min',
  },
  {
    position: 2,
    name: 'DragonGirl',
    icon: '🐉',
    resolved: 75,
    resolvedGoal: 100,
    points: 2000,
    weeklyChange: 5,
    effectiveness: 95,
    effectivenessIcon: '🌟',
    remaining: 25,
    remainingGoal: 100,
    lastUpdate: 'Hace 7 min',
  },
  {
    position: 3,
    name: 'CyberSamurai',
    icon: '🧑‍💻',
    resolved: 70,
    resolvedGoal: 100,
    points: 1850,
    weeklyChange: -2,
    effectiveness: 90,
    effectivenessIcon: '💡',
    remaining: 30,
    remainingGoal: 100,
    lastUpdate: 'Hace 9 min',
  },
  {
    position: 4,
    name: 'RocketMan',
    icon: '🚀',
    resolved: 65,
    resolvedGoal: 100,
    points: 1700,
    weeklyChange: 0,
    effectiveness: 88,
    effectivenessIcon: '🌟',
    remaining: 35,
    remainingGoal: 100,
    lastUpdate: 'Hace 11 min',
  },
  {
    position: 5,
    name: 'ShadowNinja',
    icon: '👤',
    resolved: 60,
    resolvedGoal: 100,
    points: 1550,
    weeklyChange: 12,
    effectiveness: 85,
    effectivenessIcon: '⚡',
    remaining: 40,
    remainingGoal: 100,
    lastUpdate: 'Hace 13 min',
  },
  {
    position: 6,
    name: 'PhantomCoder',
    icon: '👻',
    resolved: 55,
    resolvedGoal: 100,
    points: 1400,
    weeklyChange: -5,
    effectiveness: 82,
    effectivenessIcon: '💎',
    remaining: 45,
    remainingGoal: 100,
    lastUpdate: 'Hace 15 min',
  },
  {
    position: 7,
    name: 'NeonHacker',
    icon: '💻',
    resolved: 50,
    resolvedGoal: 100,
    points: 1250,
    weeklyChange: 8,
    effectiveness: 78,
    effectivenessIcon: '🎭',
    remaining: 50,
    remainingGoal: 100,
    lastUpdate: 'Hace 17 min',
  },
  {
    position: 8,
    name: 'VoidMaster',
    icon: '🌀',
    resolved: 45,
    resolvedGoal: 100,
    points: 1100,
    weeklyChange: -3,
    effectiveness: 75,
    effectivenessIcon: '🌪️',
    remaining: 55,
    remainingGoal: 100,
    lastUpdate: 'Hace 19 min',
  },
  {
    position: 9,
    name: 'CrystalKnight',
    icon: '💎',
    resolved: 40,
    resolvedGoal: 100,
    points: 950,
    weeklyChange: 6,
    effectiveness: 72,
    effectivenessIcon: '✨',
    remaining: 60,
    remainingGoal: 100,
    lastUpdate: 'Hace 21 min',
  },
  {
    position: 10,
    name: 'ThunderStrike',
    icon: '⚡',
    resolved: 35,
    resolvedGoal: 100,
    points: 800,
    weeklyChange: -1,
    effectiveness: 68,
    effectivenessIcon: '🔥',
    remaining: 65,
    remainingGoal: 100,
    lastUpdate: 'Hace 23 min',
  },
  {
    position: 11,
    name: 'FirePhoenix',
    icon: '🔥',
    resolved: 30,
    resolvedGoal: 100,
    points: 650,
    weeklyChange: 15,
    effectiveness: 65,
    effectivenessIcon: '🌟',
    remaining: 70,
    remainingGoal: 100,
    lastUpdate: 'Hace 25 min',
  },
  {
    position: 12,
    name: 'IceWarrior',
    icon: '❄️',
    resolved: 25,
    resolvedGoal: 100,
    points: 500,
    weeklyChange: -7,
    effectiveness: 62,
    effectivenessIcon: '💎',
    remaining: 75,
    remainingGoal: 100,
    lastUpdate: 'Hace 27 min',
  },
  {
    position: 13,
    name: 'WindRider',
    icon: '🌪️',
    resolved: 20,
    resolvedGoal: 100,
    points: 350,
    weeklyChange: 4,
    effectiveness: 58,
    effectivenessIcon: '⚡',
    remaining: 80,
    remainingGoal: 100,
    lastUpdate: 'Hace 29 min',
  },
  {
    position: 14,
    name: 'EarthGuardian',
    icon: '🌍',
    resolved: 15,
    resolvedGoal: 100,
    points: 200,
    weeklyChange: -2,
    effectiveness: 55,
    effectivenessIcon: '🛡️',
    remaining: 85,
    remainingGoal: 100,
    lastUpdate: 'Hace 31 min',
  },
  {
    position: 15,
    name: 'LightningBolt',
    icon: '⚡',
    resolved: 10,
    resolvedGoal: 100,
    points: 100,
    weeklyChange: 1,
    effectiveness: 50,
    effectivenessIcon: '💡',
    remaining: 90,
    remainingGoal: 100,
    lastUpdate: 'Hace 33 min',
  },
];



const TeamScoreSection = () => {
  return (
    <section id="team-score-section" className="w-full flex flex-col items-center py-10 px-2">
      {/* Encabezado principal */}
      <h1 className="text-4xl md:text-5xl font-bold text-center text-white mb-10 tracking-wide drop-shadow-lg">
        TABLAS DE CLASIFICACIÓN
      </h1>
      
      {/* Tablas de ranking */}
      <div className="w-full flex flex-col gap-8 items-center">
        <RankingTable
          title="Ranking de Equipos"
          type="team"
          data={teamsRanking}
        />
        <RankingTable
          title="Ranking de Usuarios"
          type="user"
          data={usersRanking}
        />
      </div>
    </section>
  );
};

export default TeamScoreSection; 