import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from 'react-query'
import { ReactQueryDevtools } from 'react-query/devtools'
import { Toaster } from 'react-hot-toast'
import { HelmetProvider } from 'react-helmet-async'
import { ErrorBoundary } from 'react-error-boundary'

import App from './App'
import { AuthProvider } from './contexts/AuthContext'
import { SocketProvider } from './contexts/SocketContext'
import { ThemeProvider } from './contexts/ThemeContext'
import ErrorFallback from './components/ErrorFallback'
import './styles/index.css'
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n
  .use(initReactI18next)
  .init({
    resources: {
      es: {
        translation: {
          'Ajustes': 'Ajustes',
          'Tema': 'Tema',
          'Claro': 'Claro',
          'Oscuro': 'Oscuro',
          'Idioma': 'Idioma',
          'Español': 'Español',
          'Inglés': 'Inglés',
          'Cerrar sesión': 'Cerrar sesión',
          'Menú': 'Menú',
          'Tienda': 'Tienda',
          'Perfil': 'Perfil',
          'Equipo': 'Equipo',
          'Ranking Equipos': 'Ranking Equipos',
          'Puntaje': 'Puntaje',
          'Personalización de Perfil': 'Personalización de Perfil',
          'Editar': 'Editar',
          'ID': 'ID',
          'Puntos': 'Puntos',
          'Ranking': 'Ranking',
          'Logros': 'Logros',
          'Logros Obtenidos': 'Logros Obtenidos',
          'Progreso de Logros': 'Progreso de Logros',
          'Gulag': 'Gulag',
          'Gulag_description': '¡Los que necesitan mejorar!',
          'Gulag_top_5_title': 'TOP 5 - Peores',
          'Gulag_rank_header': '#',
          'Gulag_player_header': 'Jugador',
          'Gulag_score_header': 'Puntaje',
          'MVP Usuario': 'MVP Usuario',
          'MVP Team': 'MVP Equipo',
          'Perfil Usuario': 'Perfil Usuario',
          'Ranking Usuarios': 'Ranking Usuarios',
          'Usuario': 'Usuario',
          'puntos_abbr': 'pts',
          'Perfil_del_jugador_destacado': '¡Perfil del jugador destacado!',
          'Estadísticas': 'ESTADÍSTICAS',
          'Vulnerabilidades_solucionadas': 'Vulnerabilidades solucionadas',
          'Críticas': 'Críticas',
          'Altas': 'Altas',
          'Medianas': 'Medianas',
          'Bajas': 'Bajas',
          'User Score': 'Puntaje Usuario',
          '¡Los mejores jugadores individuales!': '¡Los mejores jugadores individuales!',
          'TOP 3 - Usuarios': 'TOP 3 - Usuarios',
          'EQUIPO MVP': 'EQUIPO MVP',
          'El equipo más valioso del momento!': '¡El equipo más valioso del momento!',
          'Ranking del Mes': 'Ranking del Mes',
          '¡Conoce a los 5 mejores jugadores!': '¡Conoce a los 5 mejores jugadores!',
          'Jugador del mes': 'Jugador del mes',
          'TOP 5 - Jugador del mes': 'TOP 5 - Jugador del mes',
          'Ranking de Equipos (Cuatrimestral)': 'Ranking de Equipos (Cuatrimestral)',
          '¡Top equipos de 3 a 10 miembros del cuatrimestre!': '¡Top equipos de 3 a 10 miembros del cuatrimestre!',
          'TOP 5 - Equipo del Cuatrimestre': 'TOP 5 - Equipo del Cuatrimestre',
          'Jugador': 'Jugador',
          'Miembros': 'Miembros',
          'Ranking Cuatrimestral de Equipos': 'Ranking Cuatrimestral de Equipos',
          'TOP 5 EQUIPOS DEL CUATRIMESTRE': 'TOP 5 EQUIPOS DEL CUATRIMESTRE',
          'Ranking Mensual': 'Ranking Mensual',
          'TOP 5 DEL MES': 'TOP 5 DEL MES',
          'PLAYER': 'JUGADOR',
          'SCORE': 'PUNTUACIÓN',
          'RANK': 'RANGO',
          'DIAMANTE': 'DIAMANTE',
          'ORO': 'ORO',
          'PLATA': 'PLATA',
          'BRONCE': 'BRONCE',
          'Cargando perfil...': 'Cargando perfil...',
          'Error al cargar el perfil': 'Error al cargar el perfil',
          'Sin título': 'Sin título',
          'Primera Vulnerabilidad': 'Primera Vulnerabilidad',
          'Encontró su primera vulnerabilidad': 'Encontró su primera vulnerabilidad',
          'Top 10': 'Top 10',
          'Llegó al top 10 del ranking': 'Llegó al top 10 del ranking',
          'MVP': 'MVP',
          'Ganó el título de MVP': 'Ganó el título de MVP',
          'Sobreviviente del Gulag': 'Sobreviviente del Gulag',
          'Sobrevivió al evento Gulag': 'Sobrevivió al evento Gulag',
          'Capitán de Equipo': 'Capitán de Equipo',
          'Lideró un equipo exitoso': 'Lideró un equipo exitoso',
          'Cazador de Bugs': 'Cazador de Bugs',
          'Encontró 50 vulnerabilidades': 'Encontró 50 vulnerabilidades',
          'Cargando avatares...': 'Cargando avatares...',
          'Volver': 'Volver',
          'Seleccionar Avatar': 'Seleccionar Avatar',
          'Guardando...': 'Guardando...',
          'Guardar': 'Guardar',
          'Por Defecto': 'Por Defecto',
          'Premium': 'Premium',
          'Especial': 'Especial',
          'Otros': 'Otros',
          'desbloqueados': 'desbloqueados',
          '¿Cómo desbloquear más avatares?': '¿Cómo desbloquear más avatares?',
          'Avatares Premium: Compra en la tienda': 'Avatares Premium: Compra en la tienda',
          'Avatares Especiales: Logros especiales': 'Avatares Especiales: Logros especiales',
          'Eventos temporales y competiciones': 'Eventos temporales y competiciones',
          'Team Leader': 'Líder del Equipo',
          'Security Analyst': 'Analista de Seguridad',
          'Penetration Tester': 'Tester de Penetración',
          'Engineer': 'Ingeniero',
          'Reverse Engineer': 'Ingeniero Inverso',
          'SOC Analyst': 'Analista SOC',
          'Exploit Developer': 'Desarrollador de Exploits',
          'Network Specialist': 'Especialista de Red',
          'Cryptographer': 'Criptógrafo',
          'Forensic Analyst': 'Analista Forense',
          'Social Engineer': 'Ingeniero Social',
          'Bug Bounty Hunter': 'Cazador de Recompensas',
          'Malware Analyst': 'Analista de Malware',
          'Vulnerability Researcher': 'Investigador de Vulnerabilidades',
          'Nuevo Equipo': 'Nuevo Equipo',
          'Crear Equipo': 'Crear Equipo',
          'Unirse a Equipo': 'Unirse a Equipo',
          'Nombre del equipo': 'Nombre del equipo',
          'Buscar equipo...': 'Buscar equipo...',
          'Eliminar equipo': 'Eliminar equipo',
          '¿Seguro que quieres eliminar tu equipo?': '¿Seguro que quieres eliminar tu equipo?',
          '¿Seguro que quieres salir del equipo?': '¿Seguro que quieres salir del equipo?',
          'Sí': 'Sí',
          'No': 'No',
          'Salir del equipo': 'Salir del equipo',
          'Transferir liderazgo': 'Transferir liderazgo',
          '¿A quién quieres transferir el liderazgo?': '¿A quién quieres transferir el liderazgo?',
          'Transferir': 'Transferir',
          'Cancelar': 'Cancelar',
          'Agregar miembro': 'Agregar miembro',
          'Buscar usuarios...': 'Buscar usuarios...',
          'Miembros del equipo': 'Miembros del equipo',
          'Gestionar equipo': 'Gestionar equipo',
          'Crear nuevo equipo': 'Crear nuevo equipo',
          'Unirse a equipo existente': 'Unirse a equipo existente',
        }
      },
      en: {
        translation: {
          'Ajustes': 'Settings',
          'Tema': 'Theme',
          'Claro': 'Light',
          'Oscuro': 'Dark',
          'Idioma': 'Language',
          'Español': 'Spanish',
          'Inglés': 'English',
          'Cerrar sesión': 'Logout',
          'Menú': 'Menu',
          'Tienda': 'Shop',
          'Perfil': 'Profile',
          'Equipo': 'Team',
          'Ranking Equipos': 'Teams Ranking',
          'Puntaje': 'Score',
          'Personalización de Perfil': 'Profile Customization',
          'Editar': 'Edit',
          'ID': 'ID',
          'Puntos': 'Points',
          'Ranking': 'Ranking',
          'Logros': 'Achievements',
          'Logros Obtenidos': 'Achievements Unlocked',
          'Progreso de Logros': 'Achievements Progress',
          'Gulag': 'Gulag',
          'Gulag_description': 'Those who need to improve!',
          'Gulag_top_5_title': 'TOP 5 - Worst',
          'Gulag_rank_header': '#',
          'Gulag_player_header': 'Player',
          'Gulag_score_header': 'Score',
          'MVP Usuario': 'MVP User',
          'MVP Team': 'MVP Team',
          'Perfil Usuario': 'User Profile',
          'Ranking Usuarios': 'User Ranking',
          'Usuario': 'User',
          'puntos_abbr': 'pts',
          'Perfil_del_jugador_destacado': 'Featured player profile!',
          'Estadísticas': 'STATISTICS',
          'Vulnerabilidades_solucionadas': 'Vulnerabilities solved',
          'Críticas': 'Critical',
          'Altas': 'High',
          'Medianas': 'Medium',
          'Bajas': 'Low',
          'User Score': 'User Score',
          '¡Los mejores jugadores individuales!': 'The best individual players!',
          'TOP 3 - Usuarios': 'TOP 3 - Users',
          'EQUIPO MVP': 'MVP TEAM',
          'El equipo más valioso del momento!': 'The most valuable team right now!',
          'Ranking del Mes': 'Monthly Ranking',
          '¡Conoce a los 5 mejores jugadores!': 'Meet the top 5 players!',
          'Jugador del mes': 'Player of the Month',
          'TOP 5 - Jugador del mes': 'TOP 5 - Player of the Month',
          'Ranking de Equipos (Cuatrimestral)': 'Quarterly Team Ranking',
          '¡Top equipos de 3 a 10 miembros del cuatrimestre!': 'Top teams of 3 to 10 members of the quarter!',
          'TOP 5 - Equipo del Cuatrimestre': 'TOP 5 - Team of the Quarter',
          'Jugador': 'Player',
          'Miembros': 'Members',
          'Ranking Cuatrimestral de Equipos': 'Quarterly Team Ranking',
          'TOP 5 EQUIPOS DEL CUATRIMESTRE': 'TOP 5 TEAMS OF THE QUARTER',
          'Ranking Mensual': 'Monthly Ranking',
          'TOP 5 DEL MES': 'TOP 5 OF THE MONTH',
          'PLAYER': 'PLAYER',
          'SCORE': 'SCORE',
          'RANK': 'RANK',
          'DIAMANTE': 'DIAMOND',
          'ORO': 'GOLD',
          'PLATA': 'SILVER',
          'BRONCE': 'BRONZE',
          'Cargando perfil...': 'Loading profile...',
          'Error al cargar el perfil': 'Error loading profile',
          'Sin título': 'No title',
          'Primera Vulnerabilidad': 'First Vulnerability',
          'Encontró su primera vulnerabilidad': 'Found their first vulnerability',
          'Top 10': 'Top 10',
          'Llegó al top 10 del ranking': 'Reached the top 10 ranking',
          'MVP': 'MVP',
          'Ganó el título de MVP': 'Won the MVP title',
          'Sobreviviente del Gulag': 'Gulag Survivor',
          'Sobrevivió al evento Gulag': 'Survived the Gulag event',
          'Capitán de Equipo': 'Team Captain',
          'Lideró un equipo exitoso': 'Led a successful team',
          'Cazador de Bugs': 'Bug Hunter',
          'Encontró 50 vulnerabilidades': 'Found 50 vulnerabilities',
          'Cargando avatares...': 'Loading avatars...',
          'Volver': 'Back',
          'Seleccionar Avatar': 'Select Avatar',
          'Guardando...': 'Saving...',
          'Guardar': 'Save',
          'Por Defecto': 'Default',
          'Premium': 'Premium',
          'Especial': 'Special',
          'Otros': 'Others',
          'desbloqueados': 'unlocked',
          '¿Cómo desbloquear más avatares?': 'How to unlock more avatars?',
          'Avatares Premium: Compra en la tienda': 'Premium Avatars: Buy in the shop',
          'Avatares Especiales: Logros especiales': 'Special Avatars: Special achievements',
          'Eventos temporales y competiciones': 'Temporary events and competitions',
          'Team Leader': 'Team Leader',
          'Security Analyst': 'Security Analyst',
          'Penetration Tester': 'Penetration Tester',
          'Engineer': 'Engineer',
          'Reverse Engineer': 'Reverse Engineer',
          'SOC Analyst': 'SOC Analyst',
          'Exploit Developer': 'Exploit Developer',
          'Network Specialist': 'Network Specialist',
          'Cryptographer': 'Cryptographer',
          'Forensic Analyst': 'Forensic Analyst',
          'Social Engineer': 'Social Engineer',
          'Bug Bounty Hunter': 'Bug Bounty Hunter',
          'Malware Analyst': 'Malware Analyst',
          'Vulnerability Researcher': 'Vulnerability Researcher',
          'Nuevo Equipo': 'New Team',
          'Crear Equipo': 'Create Team',
          'Unirse a Equipo': 'Join Team',
          'Nombre del equipo': 'Team name',
          'Buscar equipo...': 'Search team...',
          'Eliminar equipo': 'Delete team',
          '¿Seguro que quieres eliminar tu equipo?': 'Are you sure you want to delete your team?',
          '¿Seguro que quieres salir del equipo?': 'Are you sure you want to leave the team?',
          'Sí': 'Yes',
          'No': 'No',
          'Salir del equipo': 'Leave team',
          'Transferir liderazgo': 'Transfer leadership',
          '¿A quién quieres transferir el liderazgo?': 'Who do you want to transfer leadership to?',
          'Transferir': 'Transfer',
          'Cancelar': 'Cancel',
          'Agregar miembro': 'Add member',
          'Buscar usuarios...': 'Search users...',
          'Miembros del equipo': 'Team members',
          'Gestionar equipo': 'Manage team',
          'Crear nuevo equipo': 'Create new team',
          'Unirse a equipo existente': 'Join existing team',
        }
      }
    },
    lng: localStorage.getItem('app_language') || 'es',
    fallbackLng: 'es',
    interpolation: {
      escapeValue: false,
    },
  });

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
      staleTime: 5 * 60 * 1000, // 5 minutos
    },
  },
})

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ErrorBoundary FallbackComponent={ErrorFallback}>
      <HelmetProvider>
        <QueryClientProvider client={queryClient}>
          <BrowserRouter>
            <ThemeProvider>
              <AuthProvider>
                <SocketProvider>
                  <App />
                  <Toaster
                    position="top-right"
                    toastOptions={{
                      duration: 4000,
                      style: {
                        background: '#363636',
                        color: '#fff',
                      },
                    }}
                  />
                </SocketProvider>
              </AuthProvider>
            </ThemeProvider>
          </BrowserRouter>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </HelmetProvider>
    </ErrorBoundary>
  </React.StrictMode>
) 